name: Build JSQ.exe

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MinGW via winget
        run: |
          winget install --id=MSYS2.MSYS2 -e --silent
          echo "C:\msys64\mingw64\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Compile
        run: g++ JSQ.cpp -o JSQ.exe -mwindows -lwinmm -municode -std=c++17

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: JSQ-exe
          path: JSQ.exe
